package org.account_movement_service.account_movement_service.application.interfaces.movementService;

import org.account_movement_service.account_movement_service.application.dto.MovementDTO;
import org.account_movement_service.account_movement_service.application.interfaces.genericService.BaseRegisterService;

public interface RegisterMovementService extends BaseRegisterService<MovementDTO> {
}
