package org.account_movement_service.account_movement_service.application.interfaces.accountService;

import org.account_movement_service.account_movement_service.application.dto.accountDto.AccountDTO;
import org.account_movement_service.account_movement_service.application.dto.accountDto.ResAccountDto;
import org.account_movement_service.account_movement_service.application.interfaces.genericService.BaseRegisterService;

public interface RegisterAccountService extends BaseRegisterService<ResAccountDto, AccountDTO> {
}
