package org.account_movement_service.account_movement_service.application.interfaces.accountService;

import org.account_movement_service.account_movement_service.application.dto.AccountDTO;
import org.account_movement_service.account_movement_service.application.interfaces.genericService.BaseRegisterService;

public interface RegisterAccountService extends BaseRegisterService<AccountDTO> {
}
