spring:
  application:
    name: account_movement_service
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/banck
    username: postgres
    password: javacoffe343569

server:
  port: 8082

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    use-root-path: true
  api-docs:
    path: /v1/api-docs
    groups:
      enabled: true

api:
  base:
    grpc:
      url: localhost
      port: 9090
